### PR TITLE
Refactor to ES6 & Dependency Updates

### PR DESCRIPTION
**Pull request by tarang9211**

### CODE REVIEW

**Comment by tarang9211** [comment]
@TheLarkInn

**Comment by tarang9211** [comment]
@TheLarkInn here's an updated screenshot.
screen shot 2017-01-23 at 1 35 21 am

Any suggestions about resolving the `Promise` and `should` errors? Make them globals?

**Comment by TheLarkInn** [comment]
I'll check out your branch and see if we can work through it together.

**Comment by TheLarkInn** [comment]
Hey @tarang9211 I accidentally merged this when I checked out your branch locally to master, I reverted, so would you mind reopening the PR once more.

Let me share a commit with you that fixes the errors you were seeing.

**Comment by tarang9211** [comment]
Can we re-open this?

**Pull request merged**
